/* tslint:disable */
/* eslint-disable */
/**
 * AI Proxy API
 * AI model proxy with async job support. Powered by Gin, Fx, GORM, and AWS Lambda.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

