export enum IndicatorPosition {
  TOP_RIGHT = 'TOP_RIGHT',
  TOP_LEFT = 'TOP_LEFT',
  BOTTOM_RIGHT = 'BOTTOM_RIGHT',
  BOTTOM_LEFT = 'BOTTOM_LEFT',
  TOP_CENTER = 'TOP_CENTER',
  BOTTOM_CENTER = 'BOTTOM_CENTER',
}
